parcelLab/ci

.github/workflows/yaml.yaml

We require to add a list of files exempt from linting checks.

chore: Adding a list of excluded files to the linter

---

.github/workflows/kubernetes.yaml

Reverts parcelLab/ci#3
This is currently failing production depoys

Revert "feat: adding clean up step in kubernetes workflow"

---

.github/workflows/kubernetes.yaml

https://parcellab.atlassian.net/browse/INF-1115
Moving cleanup job to the end of the workflow.

feat: adding clean up step in kubernetes workflow in the end

---

.github/workflows/kubernetes.yaml

test: adding clean up step in kubernetes workflow in the end

---

.github/workflows/yaml.yaml

Even with the "ternary" [operator](https://docs.github.com/en/actions/learn-github-actions/expressions#example) there's some issues when expanding variables in GH actions. This is more readable and less hacky.

chore: ignoring files on lint

---

.github/workflows/kubernetes.yaml

Adding token to clean up images job

feat: adding token to clean up images job

---

.github/workflows/kubernetes.yaml

feat: keep 50 old versions always

---

.github/workflows/yaml.yaml

feat: upgrading prettier version

---

.github/workflows/kubernetes.yaml

Small amount of versions to keep caused issues in product-api

feat: increasing min versions to keep to avoid issues in deployment like product-api

---

.github/workflows/kubernetesecr.yaml

https://parcellab.atlassian.net/browse/INF-1609

feat: Adding new kubernetes pipeline with ECR extra step.

---

.github/workflows/kubernetes-ecr.yaml
.github/workflows/kubernetes-options.yaml
.github/workflows/kubernetes.yaml

https://parcellab.atlassian.net/browse/INF-1653
Pushing images aso to ECR with kubernetes actions. 2 pipelines:
- Old kubernetes one modified to push to both repositories.
- New one with a parameter to choose to which repository you want to push.

feat: Changing kubernetes-ecr pipeline.

---

.github/workflows/kubernetes-options.yaml
.github/workflows/kubernetes.yaml

test: Fixing pipelines typo.

---

.github/workflows/build-and-push-image-to-ecr.yaml

https://parcellab.atlassian.net/browse/INF-1733

feat: Adding download build artifact step

---

.github/workflows/build-and-push-image-to-ecr.yaml

https://parcellab.atlassian.net/browse/INF-2081

feat: Updating GH for ECR iamge

---

.github/workflows/build-and-push-image-to-ecr.yaml

feat: Updating GHA for ECR repository

---

.github/workflows/build-and-push-image-to-ecr.yaml
.github/workflows/kubernetes.yaml

https://parcellab.atlassian.net/browse/INF-2107

feat: Upgrading download-artifact action to v4

---

.github/workflows/build-and-push-image-to-ecr.yaml

* Removing unnecessary part of the conditional
* Using input to pass trigger event to be able to use it as a conditional in the reusable workflow

fix: preview comment step conditional statement

---

.github/workflows/terraform.yaml

https://parcellab.atlassian.net/browse/INF-2148

feat: INF-2148 Upgrading GHA cache

---

.github/workflows/kubernetes.yaml

Setting default 5m timeout to 10m because it fails for `backend`

chore: increase scan timeout

---

.github/workflows/kubernetes.yaml

* add additional commit step for backend-playground with corresponding conditional check

feat: add conditional commit step for playground values

---

.github/workflows/release.yaml

https://parcellab.atlassian.net/browse/INF-2334

feat: inf-2338 update release-wizard action latest version

---

.github/workflows/kubernetes.yaml

To control where the values.yaml can be found, this is an optional field.

feat: introduce new variable deploymentRepoValuesPath 

---

.github/workflows/kubernetes.yaml

Updating path for playground with the new structure in the kubernetes workflow.

feat: updating path for playground
